* First run of ansible always fails - I suspect a version bootstrapping issue
    * .rbenv is modified in forums (this may be related to the issue above)
* fix auto-registration of new oauth2 client in LMS (insights role)
    * the new version of edx-oauth2-provider is not being installed for some reason?
* manual addition of "DEBUG: true" to /edx/etc/insights.yml in order to get django to serve static assets from "runserver"
* fix 'False', should be just false in /edx/etc/insights.yml
* had to manually run "python manage.py migrate" on the insights app
* EXTRA_SCOPES = ['permissions'] in insights base.py settings
    * LMS master rejects this scope?
* ensure hdfs://localhost:9000/data/ directory exists
    * change permissions of /edx/var/log/tracking/tracking.log to 644


* document instructions
    * vagrant up
    * as vagrant user run "/edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook -i localhost, -c loc
al analytics_single.yml"
    * sudo su hadoop
        * edx-analytics-hadoop.sh start



/edx/bin/manage.edxapp lms --settings=aws create_oauth2_client http://localhost:8110 http://localhost:8110/complete/edx-oidc/ confidential --username staff --client_name insights --client_id YOUR_OAUTH2_KEY --client_secret secret --trusted